import type { AuthRole } from '../types';

export const Labels = {
  appName: 'MedRoute',
  zone: 'Bhopal zone',
  zoneCentral: 'Bhopal Central',
  hospitalAdminTitle: 'JP Hospital — Admin',
  defaultHospitalName: 'JP Hospital',
  languageDisplay: 'Hindi / English',
  profileName: 'Amit Kumar',
  helpdeskPhone: '0755-XXXXXXX',
  noData: 'No data available',
  featureComingSoon: 'Feature coming soon',
  newEmergencyTitle: 'New Emergency',
  newEmergencyButton: '+ New Emergency',
  rerouteTitle: 'Reroute to different hospital',
  arrivedTitle: 'Arrived at hospital',
  arrivedMessage: 'Mark this run as completed at the hospital?',
  contactHelpdesk: 'Contact hospital helpdesk',
  specialistReady: 'Neurosurgeon on standby',
  liveAlerts: 'Live alerts',
  activeCases: 'Active cases',
  updateCapacity: 'Update capacity',
  incomingPatients: 'Incoming patients',
  onCallSpecialists: 'On-call specialists',
  addSpecialist: '+ Add',
  freeUp: '− Free up',
  occupy: '+ Occupy',
  trackPatient: 'Track patient',
  safeStatus: 'Safe',
  timeline: 'Timeline',
  notifications: 'Notifications',
  zoneAndLanguage: 'Zone & language',
  zoneRow: 'Zone',
  languageRow: 'Language',
  criticalAlerts: 'Critical alerts',
  caseUpdates: 'Case updates',
  shiftReminders: 'Shift reminders',
  onShift: 'On-shift',
  dispatcherHome: 'Dispatcher Home',
  navigation: 'Navigation',
  beds: 'Beds',
  incoming: 'Incoming',
  settings: 'Settings',
  home: 'Home',
  map: 'Map',
  cases: 'Cases',
  navigate: 'Navigate',
  track: 'Track',
  login: 'Login',
  logout: 'Logout',
  employeeIdLabel: 'Employee/Hospital ID',
  passwordLabel: 'Password',
  activeEmergencies: 'Active Emergencies',
  bedsFreeCitywide: 'Beds Free city-wide',
  patientInfo: 'Patient info',
  vitalsLive: 'Vitals (live)',
  routing: 'Routing',
  rerouteHospital: 'Reroute to different hospital',
  preNotificationTitle: 'JP Hospital — Bed 12 reserved',
  patientVitalsInput: 'Patient vitals input',
  arrivedAtHospital: 'Arrived at hospital',
  assignedHospital: 'Assigned hospital',
  eta: 'ETA',
  specialistReadyLabel: 'Specialist ready',
  selectHospital: 'Select hospital',
  cancel: 'Cancel',
  ok: 'OK',
  navEtaBadge: '6 min',
  roleLabels: {
    dispatcher: 'Control room',
    ambulance: 'Field crew',
    hospital: 'Admin staff',
    family: 'Track patient',
  } as Record<AuthRole, string>,
  roleTitle: (role: AuthRole) => Labels.roleLabels[role],
};
