import type { AlertItem, CaseItem, FamilyPatient, Hospital } from '../types';

export const mockHospitals: Hospital[] = [
  {
    id: 'h1',
    name: 'JP Hospital',
    address: 'Bhopal, MP',
    distance: '3.2 km',
    status: 'available',
    lat: 23.2599,
    lng: 77.4126,
    icuTotal: 25,
    icuFree: 18,
    generalTotal: 80,
    generalFree: 62,
    otTotal: 3,
    otFree: 2,
    specialists: ['Neurosurgeon', 'Cardiologist', 'Ortho'],
  },
  {
    id: 'h2',
    name: 'Hamidia Hospital',
    address: 'Bhopal, MP',
    distance: '5.1 km',
    status: 'moderate',
    lat: 23.2635,
    lng: 77.4018,
    icuTotal: 20,
    icuFree: 8,
    generalTotal: 80,
    generalFree: 48,
    otTotal: 2,
    otFree: 1,
    specialists: ['Cardiologist', 'General Surgeon'],
  },
  {
    id: 'h3',
    name: 'AIIMS Bhopal',
    address: 'Saket Nagar, Bhopal',
    distance: '7.4 km',
    status: 'full',
    lat: 23.2156,
    lng: 77.4304,
    icuTotal: 34,
    icuFree: 2,
    generalTotal: 120,
    generalFree: 26,
    otTotal: 4,
    otFree: 0,
    specialists: ['Neurosurgeon'],
  },
  {
    id: 'h4',
    name: 'Chirayu Medical',
    address: 'Bhopal, MP',
    distance: '6.2 km',
    status: 'available',
    lat: 23.2401,
    lng: 77.389,
    icuTotal: 15,
    icuFree: 12,
    generalTotal: 40,
    generalFree: 26,
    otTotal: 4,
    otFree: 3,
    specialists: ['Ortho', 'Burns Specialist'],
  },
];

export const mockCases: CaseItem[] = [
  {
    id: 'E-041',
    type: 'Road accident — head trauma',
    severity: 'critical',
    patientAge: 34,
    patientGender: 'M',
    ambulanceId: 'Amb-07',
    location: 'TT Nagar',
    assignedHospital: 'JP Hospital',
    eta: '6 min',
    status: 'enroute',
    vitals: { hr: 118, bp: '90/60', spo2: 92, gcs: 11 },
  },
  {
    id: 'E-039',
    type: 'Cardiac arrest',
    severity: 'critical',
    patientAge: 58,
    patientGender: 'M',
    ambulanceId: 'Amb-03',
    location: 'Kolar Road',
    assignedHospital: 'Chirayu Medical',
    eta: '9 min',
    status: 'enroute',
    vitals: { hr: 42, bp: '70/40', spo2: 88, gcs: 8 },
  },
  {
    id: 'E-038',
    type: 'Burns — 40% body',
    severity: 'serious',
    patientAge: 27,
    patientGender: 'F',
    ambulanceId: 'Amb-11',
    location: 'Berasia Road',
    assignedHospital: 'Hamidia Hospital',
    eta: '14 min',
    status: 'enroute',
    vitals: { hr: 102, bp: '100/70', spo2: 96, gcs: 14 },
  },
  {
    id: 'E-036',
    type: 'Fracture — multiple',
    severity: 'moderate',
    patientAge: 45,
    patientGender: 'M',
    ambulanceId: 'Amb-02',
    location: 'Habibganj',
    assignedHospital: 'Hamidia Hospital',
    eta: 'Done',
    status: 'admitted',
    vitals: { hr: 88, bp: '120/80', spo2: 98, gcs: 15 },
  },
];

export const mockAlerts: AlertItem[] = [
  {
    id: 1,
    type: 'critical',
    message: 'AIIMS ICU at 94% — rerouting incoming cases',
    time: 'Now',
  },
  {
    id: 2,
    type: 'warning',
    message: 'Hamidia OT closing for cleaning (30 min)',
    time: '2m ago',
  },
  {
    id: 3,
    type: 'info',
    message: 'Neurosurgeon available at JP Hospital until 22:00',
    time: '5m ago',
  },
  {
    id: 4,
    type: 'info',
    message: 'Amb-07 reporting heavy traffic on NH-12',
    time: '7m ago',
  },
  {
    id: 5,
    type: 'warning',
    message: 'Chirayu blood bank: O-ve stock low',
    time: '11m ago',
  },
];

export const mockFamilyPatient: FamilyPatient = {
  name: 'Ramesh Kumar',
  caseId: 'E-041',
  status: 'admitted',
  hospital: 'JP Hospital',
  ward: 'ICU — Bed 12',
  doctor: 'Dr. Sharma (Neurosurgeon)',
  timeline: [
    { label: 'Emergency reported', sub: '9:22 AM · TT Nagar', done: true },
    { label: 'Ambulance dispatched', sub: '9:24 AM · Amb-07', done: true },
    { label: 'Routed to JP Hospital', sub: '9:25 AM · ICU bed reserved', done: true },
    { label: 'Admitted to ICU', sub: '9:31 AM · Treatment ongoing', done: false },
  ],
};
